/**
 * A genuine, minimal, one-page PDF for the demo contract-review room.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS IS A REAL PDF AND NOT A TEXT FILE RENAMED
 *
 * The whole point of attaching a file to the demo is to exercise the actual
 * `file_read` / `document_extract` path — a `.txt` renamed to `.pdf` would
 * bypass `unpdf` entirely and prove nothing about the PDF pipeline specifically.
 * Written by hand rather than pulled from a library: the structure is small
 * enough that hand-writing it is less code than a dependency, and it means the
 * exact bytes are auditable in this file rather than generated by something
 * this repository does not control.
 *
 * The xref offsets are computed, not hardcoded, so editing the clause text
 * below cannot silently produce a corrupt file — `tests/demo/sample-pdf.test.ts`
 * additionally round-trips the output through the same extractor the agent
 * uses, so "this parses" is asserted, not assumed.
 */

const CLAUSES = [
  'MASTER SERVICES AGREEMENT (DRAFT)',
  '',
  'Between Meridian Holdings Ltd and the Client.',
  '',
  '1. Term. This Agreement commences on the Effective Date and continues for',
  '   twelve (12) months, renewing automatically for successive twelve-month',
  '   periods unless either party gives ninety (90) days written notice.',
  '',
  '2. Governing Law. This Agreement is governed by the laws of England and',
  '   Wales, without regard to conflict-of-law principles.',
  '',
  '3. Termination. Either party may terminate for material breach not cured',
  '   within thirty (30) days of written notice.',
];

export function sampleContractPdf(): Uint8Array {
  return buildPdf(CLAUSES);
}

/** One-page PDF, uncompressed content stream, Helvetica. */
function buildPdf(lines: string[]): Uint8Array {
  const escaped = lines.map((l) => l.replace(/([\\()])/g, '\\$1'));
  const body =
    'BT\n/F1 11 Tf\n72 720 Td\n15 TL\n' +
    escaped.map((l) => `(${l}) Tj T*`).join('\n') +
    '\nET';

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] ' +
      '/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${body.length} >>\nstream\n${body}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  objects.forEach((obj, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefAt = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
}
